;;; ast-grep-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ast-grep.el

(autoload 'ast-grep-search "ast-grep" "\
Search for ast-grep PATTERN in DIRECTORY.

PATTERN is an ast-grep pattern string (e.g., \\='$A && $A()\\=').
DIRECTORY defaults to current directory if not specified.

Interactively, prompts for pattern and uses current directory.
Uses async search with `consult' if available.
Otherwise sync with `completing-read'.
Selecting a result jumps to the match location.

Example patterns:
  \\='console.log($A)\\='     - Find console.log calls
  \\='$A && $A()\\='          - Find conditional function calls
  \\='function $NAME() {}\\=' - Find function declarations

(fn PATTERN &optional DIRECTORY)" t)
(autoload 'ast-grep-project "ast-grep" "\
Search for ast-grep PATTERN in current project.

PATTERN is an ast-grep pattern string (e.g., \\='$A && $A()\\=').

Searches recursively from the project root directory.
Requires being in a project (detected via project.el).
Uses async search with `consult' if available.
Otherwise sync with `completing-read'.

This is equivalent to `ast-grep-search' with project root as directory.

(fn PATTERN)" t)
(autoload 'ast-grep-directory "ast-grep" "\
Search for ast-grep PATTERN in specified DIRECTORY.

PATTERN is an ast-grep pattern string (e.g., \\='$A && $A()\\=').
DIRECTORY is the target directory path (supports ~ expansion).

Interactively, prompts for both pattern and directory.
Searches recursively from the specified directory.
Uses async search with `consult' if available.
Otherwise sync with `completing-read'.

(fn PATTERN DIRECTORY)" t)
(autoload 'ast-grep-mode "ast-grep" "\
Minor mode for ast-grep integration.

This is a minor mode.  If called interactively, toggle the
`ast-grep mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `ast-grep-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "ast-grep" '("ast-grep-"))

;;; End of scraped data

(provide 'ast-grep-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ast-grep-autoloads.el ends here
